server:
  port: 9000
  # 采用的默认数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/points_mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: anzhen
    password: Anzhen3531.
    driver-class-name: com.mysql.cj.jdbc.Driver
