server:
  port: 9990
spring:
  datasource:
    url: jdbc:mysql://192.168.0.104:3306/points_mall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: anzhen
    password: Anzhen3531.
    driver-class-name: com.mysql.cj.jdbc.Driver